# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_operations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple_operations.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17simple_operations.proto\"\x07\n\x05\x45mpty\"\x1a\n\tLongParam\x12\r\n\x05value\x18\x01 \x01(\x03\"\x89\x01\n\x0f\x45ightLongsParam\x12\r\n\x05long1\x18\x01 \x01(\x03\x12\r\n\x05long2\x18\x02 \x01(\x03\x12\r\n\x05long3\x18\x03 \x01(\x03\x12\r\n\x05long4\x18\x04 \x01(\x03\x12\r\n\x05long5\x18\x05 \x01(\x03\x12\r\n\x05long6\x18\x06 \x01(\x03\x12\r\n\x05long7\x18\x07 \x01(\x03\x12\r\n\x05long8\x18\x08 \x01(\x03\"\x19\n\x08StrParam\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0c\x43omplexParam\x12\x0f\n\x07\x63omplex\x18\x01 \x01(\x0c\x32\xd7\x01\n\x0cRemoteTester\x12\x1d\n\tEmptyCall\x12\x06.Empty\x1a\x06.Empty\"\x00\x12$\n\x08LongCall\x12\n.LongParam\x1a\n.LongParam\"\x00\x12\x30\n\x0e\x45ightLongCalls\x12\x10.EightLongsParam\x1a\n.LongParam\"\x00\x12!\n\x07StrCall\x12\t.StrParam\x1a\t.StrParam\"\x00\x12-\n\x0b\x43omplexCall\x12\r.ComplexParam\x1a\r.ComplexParam\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=34,
)


_LONGPARAM = _descriptor.Descriptor(
  name='LongParam',
  full_name='LongParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='LongParam.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=62,
)


_EIGHTLONGSPARAM = _descriptor.Descriptor(
  name='EightLongsParam',
  full_name='EightLongsParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='long1', full_name='EightLongsParam.long1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long2', full_name='EightLongsParam.long2', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long3', full_name='EightLongsParam.long3', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long4', full_name='EightLongsParam.long4', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long5', full_name='EightLongsParam.long5', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long6', full_name='EightLongsParam.long6', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long7', full_name='EightLongsParam.long7', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long8', full_name='EightLongsParam.long8', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=202,
)


_STRPARAM = _descriptor.Descriptor(
  name='StrParam',
  full_name='StrParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StrParam.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=229,
)


_COMPLEXPARAM = _descriptor.Descriptor(
  name='ComplexParam',
  full_name='ComplexParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='complex', full_name='ComplexParam.complex', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=262,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['LongParam'] = _LONGPARAM
DESCRIPTOR.message_types_by_name['EightLongsParam'] = _EIGHTLONGSPARAM
DESCRIPTOR.message_types_by_name['StrParam'] = _STRPARAM
DESCRIPTOR.message_types_by_name['ComplexParam'] = _COMPLEXPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'simple_operations_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

LongParam = _reflection.GeneratedProtocolMessageType('LongParam', (_message.Message,), dict(
  DESCRIPTOR = _LONGPARAM,
  __module__ = 'simple_operations_pb2'
  # @@protoc_insertion_point(class_scope:LongParam)
  ))
_sym_db.RegisterMessage(LongParam)

EightLongsParam = _reflection.GeneratedProtocolMessageType('EightLongsParam', (_message.Message,), dict(
  DESCRIPTOR = _EIGHTLONGSPARAM,
  __module__ = 'simple_operations_pb2'
  # @@protoc_insertion_point(class_scope:EightLongsParam)
  ))
_sym_db.RegisterMessage(EightLongsParam)

StrParam = _reflection.GeneratedProtocolMessageType('StrParam', (_message.Message,), dict(
  DESCRIPTOR = _STRPARAM,
  __module__ = 'simple_operations_pb2'
  # @@protoc_insertion_point(class_scope:StrParam)
  ))
_sym_db.RegisterMessage(StrParam)

ComplexParam = _reflection.GeneratedProtocolMessageType('ComplexParam', (_message.Message,), dict(
  DESCRIPTOR = _COMPLEXPARAM,
  __module__ = 'simple_operations_pb2'
  # @@protoc_insertion_point(class_scope:ComplexParam)
  ))
_sym_db.RegisterMessage(ComplexParam)



_REMOTETESTER = _descriptor.ServiceDescriptor(
  name='RemoteTester',
  full_name='RemoteTester',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=265,
  serialized_end=480,
  methods=[
  _descriptor.MethodDescriptor(
    name='EmptyCall',
    full_name='RemoteTester.EmptyCall',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LongCall',
    full_name='RemoteTester.LongCall',
    index=1,
    containing_service=None,
    input_type=_LONGPARAM,
    output_type=_LONGPARAM,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EightLongCalls',
    full_name='RemoteTester.EightLongCalls',
    index=2,
    containing_service=None,
    input_type=_EIGHTLONGSPARAM,
    output_type=_LONGPARAM,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StrCall',
    full_name='RemoteTester.StrCall',
    index=3,
    containing_service=None,
    input_type=_STRPARAM,
    output_type=_STRPARAM,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ComplexCall',
    full_name='RemoteTester.ComplexCall',
    index=4,
    containing_service=None,
    input_type=_COMPLEXPARAM,
    output_type=_COMPLEXPARAM,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTETESTER)

DESCRIPTOR.services_by_name['RemoteTester'] = _REMOTETESTER

# @@protoc_insertion_point(module_scope)
