# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import simple_operations_pb2 as simple__operations__pb2


class RemoteTesterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.EmptyCall = channel.unary_unary(
        '/RemoteTester/EmptyCall',
        request_serializer=simple__operations__pb2.Empty.SerializeToString,
        response_deserializer=simple__operations__pb2.Empty.FromString,
        )
    self.LongCall = channel.unary_unary(
        '/RemoteTester/LongCall',
        request_serializer=simple__operations__pb2.LongParam.SerializeToString,
        response_deserializer=simple__operations__pb2.LongParam.FromString,
        )
    self.EightLongCalls = channel.unary_unary(
        '/RemoteTester/EightLongCalls',
        request_serializer=simple__operations__pb2.EightLongsParam.SerializeToString,
        response_deserializer=simple__operations__pb2.LongParam.FromString,
        )
    self.StrCall = channel.unary_unary(
        '/RemoteTester/StrCall',
        request_serializer=simple__operations__pb2.StrParam.SerializeToString,
        response_deserializer=simple__operations__pb2.StrParam.FromString,
        )
    self.ComplexCall = channel.unary_unary(
        '/RemoteTester/ComplexCall',
        request_serializer=simple__operations__pb2.ComplexParam.SerializeToString,
        response_deserializer=simple__operations__pb2.ComplexParam.FromString,
        )


class RemoteTesterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def EmptyCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LongCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EightLongCalls(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StrCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ComplexCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RemoteTesterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'EmptyCall': grpc.unary_unary_rpc_method_handler(
          servicer.EmptyCall,
          request_deserializer=simple__operations__pb2.Empty.FromString,
          response_serializer=simple__operations__pb2.Empty.SerializeToString,
      ),
      'LongCall': grpc.unary_unary_rpc_method_handler(
          servicer.LongCall,
          request_deserializer=simple__operations__pb2.LongParam.FromString,
          response_serializer=simple__operations__pb2.LongParam.SerializeToString,
      ),
      'EightLongCalls': grpc.unary_unary_rpc_method_handler(
          servicer.EightLongCalls,
          request_deserializer=simple__operations__pb2.EightLongsParam.FromString,
          response_serializer=simple__operations__pb2.LongParam.SerializeToString,
      ),
      'StrCall': grpc.unary_unary_rpc_method_handler(
          servicer.StrCall,
          request_deserializer=simple__operations__pb2.StrParam.FromString,
          response_serializer=simple__operations__pb2.StrParam.SerializeToString,
      ),
      'ComplexCall': grpc.unary_unary_rpc_method_handler(
          servicer.ComplexCall,
          request_deserializer=simple__operations__pb2.ComplexParam.FromString,
          response_serializer=simple__operations__pb2.ComplexParam.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RemoteTester', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
